package ui

import (
	"fmt"
	"os"
	"strings"
)

// SVGBurnMeter holds data for SVG generation
type SVGBurnMeter struct {
	TotalRisk  float64
	Threshold  float64
	IssueCount int
}

// GenerateBurnSVG creates an animated SVG burn meter and writes it to a file
func GenerateBurnSVG(meter SVGBurnMeter, outputPath string) error {
	ratio := meter.TotalRisk / meter.Threshold
	if ratio > 1.0 {
		ratio = 1.0
	}

	// Determine flame color based on intensity
	flameColor := "#5DCAA5" // mint (safe)
	if ratio > 0.75 {
		flameColor = "#F09595" // red (inferno)
	} else if ratio > 0.6 {
		flameColor = "#ED93B1" // pink (on fire)
	} else if ratio > 0.25 {
		flameColor = "#FAC775" // butter (sweating)
	}

	// SVG with embedded CSS animations
	svg := fmt.Sprintf(`<svg viewBox="0 0 400 300" xmlns="http://www.w3.org/2000/svg">
  <defs>
    <style>
      @keyframes flicker {
        0%% { opacity: 0.6; }
        50%% { opacity: 1.0; }
        100%% { opacity: 0.6; }
      }
      @keyframes flameWave {
        0%% { transform: scaleY(0.8); }
        50%% { transform: scaleY(1.1); }
        100%% { transform: scaleY(0.8); }
      }
      @keyframes glow {
        0%% { filter: drop-shadow(0 0 8px %s); }
        50%% { filter: drop-shadow(0 0 16px %s); }
        100%% { filter: drop-shadow(0 0 8px %s); }
      }
      .header { font-family: monospace; font-size: 20px; font-weight: bold; text-anchor: middle; fill: #ED93B1; }
      .label { font-family: monospace; font-size: 14px; text-anchor: middle; fill: #AFA9EC; }
      .value { font-family: monospace; font-size: 18px; font-weight: bold; text-anchor: middle; fill: %s; }
      .flame { animation: flicker 0.4s infinite, flameWave 0.6s infinite; transform-origin: center; }
      .glow-text { animation: glow 1s infinite; }
    </style>
  </defs>

  <!-- Background -->
  <rect width="400" height="300" fill="#0d0713" />

  <!-- Header -->
  <text x="200" y="35" class="header glow-text">🔥 FINOPS BURN METER</text>

  <!-- Cost Display -->
  <text x="200" y="80" class="label">PROJECTED COST</text>
  <text x="200" y="105" class="value">$%.2f USD</text>

  <!-- Budget Display -->
  <text x="80" y="150" class="label">BUDGET</text>
  <text x="80" y="175" class="value">$%.2f</text>

  <text x="320" y="150" class="label">REMAINING</text>
  <text x="320" y="175" class="value">$%.2f</text>

  <!-- Burn Intensity Bar -->
  <rect x="50" y="200" width="300" height="20" fill="#1a0e28" stroke="#AFA9EC" stroke-width="1" />
  <rect x="50" y="200" width="%.0f" height="20" fill="%s" class="flame" />

  <!-- Status Text -->
  <text x="200" y="245" class="label">Issues: %d</text>
  <text x="200" y="270" class="label">Intensity: %.1f%%</text>

  <!-- Footer -->
  <text x="200" y="295" class="label" style="font-size: 11px;">Generated by finops-guard</text>
</svg>`,
		flameColor, flameColor, flameColor,
		flameColor,
		meter.TotalRisk,
		meter.Threshold,
		meter.Threshold-meter.TotalRisk,
		300.0*ratio,
		flameColor,
		meter.IssueCount,
		ratio*100,
	)

	if err := os.WriteFile(outputPath, []byte(svg), 0644); err != nil {
		return fmt.Errorf("failed to write SVG: %w", err)
	}

	return nil
}

// GeneratePRComment creates a Markdown PR comment with thermal receipt and SVG reference
func GeneratePRComment(meter SVGBurnMeter, issues []Issue, svgPath string) string {
	var buf strings.Builder

	// SVG reference (relative path for GitHub)
	buf.WriteString(fmt.Sprintf("![Burn Meter](%s)\n\n", svgPath))

	// Thermal printer receipt
	buf.WriteString("```\n")
	buf.WriteString(" ═══════════════════════════════════════════════════\n")
	buf.WriteString("        FINOPS-GUARD ★ COST RECEIPT\n")
	buf.WriteString("        Virtual CFO · Automated Analysis\n")
	buf.WriteString(" ───────────────────────────────────────────────────\n")

	// Line items
	if len(issues) == 0 {
		buf.WriteString("  NO ISSUES DETECTED · SAFE TO MERGE\n")
	} else {
		for i, issue := range issues {
			cost := issue.EstCostRisk
			buf.WriteString(fmt.Sprintf("  %d× %s\n", i+1, strings.ToUpper(issue.RuleName)))
			buf.WriteString(fmt.Sprintf("     %s:%d  $%.2f/run\n", issue.FilePath, issue.LineNumber, cost))
		}
	}

	buf.WriteString(" ───────────────────────────────────────────────────\n")
	buf.WriteString(fmt.Sprintf("  SUBTOTAL ................. $%.2f\n", meter.TotalRisk))
	buf.WriteString(fmt.Sprintf("  BUDGET REMAINING ........ $%.2f\n", meter.Threshold-meter.TotalRisk))

	// Status
	status := "SAFE"
	if meter.TotalRisk/meter.Threshold > 0.75 {
		status = "INFERNO"
	} else if meter.TotalRisk/meter.Threshold > 0.6 {
		status = "ON FIRE"
	} else if meter.TotalRisk/meter.Threshold > 0.25 {
		status = "SWEATING"
	}
	buf.WriteString(fmt.Sprintf("  STATUS .................. %s\n", status))

	buf.WriteString(" ───────────────────────────────────────────────────\n")
	buf.WriteString("   NO REFUNDS. CLOUD BILLS ARE FOREVER.\n")
	buf.WriteString("      thank you, come again 🧾\n")
	buf.WriteString(" ═══════════════════════════════════════════════════\n")
	buf.WriteString("```\n")

	return buf.String()
}

// Issue is a minimal issue representation for PR comments
type Issue struct {
	FilePath    string
	LineNumber  int
	RuleName    string
	EstCostRisk float64
}
